### PR TITLE
Updating Login ui and app icon

### PR DESCRIPTION
**Pull request by yvettecook**
| Before | After |
| ------ | ----- |
|  screen shot 2016-06-16 at 09 55 35 | screen shot 2016-06-15 at 11 27 30 |

Added some more AutoLayout extensions too

### CODE REVIEW

**Comment by blundell** [comment]
can I see a before screenshot?

**Comment by yvettecook** [comment]
@blundell - et voila!

**Comment by blundell** [comment]
LGTM 👍 :)

**Comment by alexstyl** [comment]
This looks so nice! 

👍 LGTM

**Pull request merged**
