### PR TITLE
Adds a java app that parses slack for text

### PR DESCRIPTION
**Pull request by blundell**
- We can now parse the general channel for the #eNews newsletter
 - MISSING a lot of tests :o

### CODE REVIEW

**Comment by ouchadam** [comment]
shame about all the noise the gradle wrapper adds but otherwise good stuff! :+1:

**Comment by xrigau** [comment]
:+1:

**Comment by blundell** [comment]
can someone sheep?

**Comment by blundell** [comment]
^ any chance of a murge

**Comment by juankysoriano** [comment]
I haven't seen anything too weird, and being this an spike... LGTM :+1:

**Pull request merged**
