### PR TITLE
[Dashboards] Apply styles

### PR DESCRIPTION
**Pull request by xrigau**
Apply styles from [slacker](https://github.com/novoda/spikes/tree/master/slacker).

Since most styles were used in all widgets, we've created a `dashboards-common.scss` file and we include that file in the components that need them.

We've also separated the novoda header to a new component to keep the main component clean.

Gif |
---|
stylessss |

Paired with @florianmski

### CODE REVIEW

**Comment by xrigau** [comment]
Should be good to go now 🌮

**Comment by takecare** [comment]
🌯

**Comment by frapontillo** [comment]
I am Friday therefore I :shipit:

**Comment by ouchadam** [comment]
no fade between widgets 👻

**Pull request merged**
