### PR TITLE
React/PT-67/hello world

### PR DESCRIPTION
**Pull request by gbasile**
Created a basic component that implement a view with the text "Hello World".
Component is then reused for both iOS and Android

| iOS | Android |
| --- | --- |
| screen shot 2016-05-09 at 16 42 42 | screen shot 2016-05-09 at 16 41 52 |

Tests: 
Added a simple demo test 

paired with @danybony

### CODE REVIEW

**Comment by blundell** [comment]
any screen shots 👅 lacking some PR etiquette

**Comment by danybony** [comment]
PR updated with some exciting screenshots for the two platforms XD
Also, we added `eslint` static analysis and a simple temo test in order to test CI integration

**Comment by blundell** [comment]
sick screenshots 👍 took 1hr 45mins in between 😱 :-)

**Comment by eduardb** [comment]
LGTM 🚢

**Pull request merged**
