### PR TITLE
Makefest - MVP for simon says spike

### PR DESCRIPTION
**Pull request by blundell**
simon-demo

An MVP that shows a sequence that you need to copy.

Code is gross .. but works.

Needs some aesthetic improvements :-) feel free to get invovled!

### CODE REVIEW

**Comment by xrigau** [comment]
I thought the Simon Says game always adds one to the end instead of random every time?

so it'd be:
`1`
`1 1`
`1 1 4`
`1 1 4 2` etc.

**Comment by xrigau** [comment]
https://www.youtube.com/watch?v=4YhVyt4q5HI

**Comment by blundell** [comment]
That is easily changeable, I thought that as well but random works work ( fork it and play :-) ) after you've played let me know if you think it should change!

**Comment by xrigau** [comment]
simon says :shipit:

**Pull request merged**
